import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding started...");

  // 1. Seed Admin
  const adminEmail = "admin@trinetra.com";
  const existingAdmin = await prisma.user.findUnique({
    where: { email: adminEmail },
  });

  if (!existingAdmin) {
    const passwordHash = await bcrypt.hash("Password@123", 10);
    await prisma.user.create({
      data: {
        name: "Trinetra Admin",
        email: adminEmail,
        mobile: "9999999999",
        college: "Trinetra Drones & Robotics",
        course: "Admin Control",
        password: passwordHash,
        role: "ADMIN",
      },
    });
    console.log("Admin seeded successfully.");
  } else {
    console.log("Admin already exists.");
  }

  // 2. Define Exams and Questions
  const examData = [
    {
      subject: "Reasoning exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "Look at this series: 2, 1, (1/2), (1/4), ... What number should come next?",
          optionA: "1/3",
          optionB: "1/8",
          optionC: "2/8",
          optionD: "1/16",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Find the odd one out.",
          optionA: "Gold",
          optionB: "Silver",
          optionC: "Copper",
          optionD: "Wood",
          correctAnswer: "D",
          difficulty: "Easy",
        },
        {
          question: "If A is B's brother, B is C's sister, how is C related to A?",
          optionA: "Brother",
          optionB: "Sister",
          optionC: "Brother or Sister",
          optionD: "Cousin",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "Which word does not belong with the others?",
          optionA: "parsley",
          optionB: "basil",
          optionC: "dill",
          optionD: "mayonnaise",
          correctAnswer: "D",
          difficulty: "Easy",
        },
        {
          question: "CUP : LIP :: BIRD : ?",
          optionA: "GRASS",
          optionB: "FOREST",
          optionC: "BEAK",
          optionD: "BUSH",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "Melt : Liquid :: Freeze : ?",
          optionA: "Ice",
          optionB: "Solid",
          optionC: "Condense",
          optionD: "Push",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Safe : Secure :: Protect : ?",
          optionA: "Guard",
          optionB: "Lock",
          optionC: "Sure",
          optionD: "Conserve",
          correctAnswer: "A",
          difficulty: "Easy",
        },
        {
          question: "Odometer is to mileage as compass is to:",
          optionA: "speed",
          optionB: "hiking",
          optionC: "needle",
          optionD: "direction",
          correctAnswer: "D",
          difficulty: "Easy",
        },
        {
          question: "Choose the word that is a synonym of 'VIGILANT'.",
          optionA: "Watchful",
          optionB: "Careless",
          optionC: "Hostile",
          optionD: "Lazy",
          correctAnswer: "A",
          difficulty: "Medium",
        },
        {
          question: "If in a code language, PAINT is written as 74128, how is PATIN written?",
          optionA: "74218",
          optionB: "74128",
          optionC: "74281",
          optionD: "71428",
          correctAnswer: "A",
          difficulty: "Hard",
        },
      ],
    },
    {
      subject: "Aptitude exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "What is the average of the first five prime numbers?",
          optionA: "5.6",
          optionB: "3.6",
          optionC: "4.8",
          optionD: "5.0",
          correctAnswer: "A",
          difficulty: "Medium",
        },
        {
          question: "A sum of money at simple interest amounts to $815 in 3 years and to $854 in 4 years. The sum is:",
          optionA: "650",
          optionB: "690",
          optionC: "698",
          optionD: "700",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?",
          optionA: "120m",
          optionB: "180m",
          optionC: "324m",
          optionD: "150m",
          correctAnswer: "D",
          difficulty: "Medium",
        },
        {
          question: "If 20% of a = b, then b% of 20 is the same as:",
          optionA: "4% of a",
          optionB: "5% of a",
          optionC: "20% of a",
          optionD: "None of these",
          correctAnswer: "A",
          difficulty: "Hard",
        },
        {
          question: "A, B and C can do a piece of work in 20, 30 and 60 days respectively. In how many days can A do the work if he is assisted by B and C on every third day?",
          optionA: "12 days",
          optionB: "15 days",
          optionC: "16 days",
          optionD: "18 days",
          correctAnswer: "B",
          difficulty: "Hard",
        },
        {
          question: "The ratio between the speeds of two trains is 7:8. If the second train runs 400 km in 4 hours, then the speed of the first train is:",
          optionA: "70 km/h",
          optionB: "75 km/h",
          optionC: "84 km/h",
          optionD: "87.5 km/h",
          correctAnswer: "D",
          difficulty: "Medium",
        },
        {
          question: "A person crosses a 600 m long street in 5 minutes. What is his speed in km per hour?",
          optionA: "3.6",
          optionB: "7.2",
          optionC: "8.4",
          optionD: "10",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:",
          optionA: "15",
          optionB: "16",
          optionC: "18",
          optionD: "25",
          correctAnswer: "B",
          difficulty: "Hard",
        },
        {
          question: "What is the probability of getting a sum of 9 from two throws of a dice?",
          optionA: "1/6",
          optionB: "1/8",
          optionC: "1/9",
          optionD: "1/12",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "Find the highest common factor of 36 and 84.",
          optionA: "4",
          optionB: "6",
          optionC: "12",
          optionD: "18",
          correctAnswer: "C",
          difficulty: "Easy",
        },
      ],
    },
    {
      subject: "robotics exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "What is the name for information sent from robot sensors to robot controllers?",
          optionA: "temperature",
          optionB: "pressure",
          optionC: "feedback",
          optionD: "signal",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "Which of the following is NOT an actuator in robotics?",
          optionA: "DC Motor",
          optionB: "Ultrasonic Sensor",
          optionC: "Servo Motor",
          optionD: "Stepper Motor",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "The number of independent movements a robot manipulator can perform is called its:",
          optionA: "Degrees of freedom",
          optionB: "Joint range",
          optionC: "Velocity profile",
          optionD: "Path planning",
          correctAnswer: "A",
          difficulty: "Medium",
        },
        {
          question: "What is the primary function of a robot's end effector?",
          optionA: "To process sensor data",
          optionB: "To control motors",
          optionC: "To interact with the environment",
          optionD: "To power the robot",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "Which coordinate system has three perpendicular linear axes?",
          optionA: "Cylindrical",
          optionB: "Spherical",
          optionC: "Cartesian",
          optionD: "Articulated",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "A robot joint that rotates around an axis perpendicular to the link is called:",
          optionA: "Revolute",
          optionB: "Prismatic",
          optionC: "Spherical",
          optionD: "Cylindrical",
          correctAnswer: "A",
          difficulty: "Easy",
        },
        {
          question: "What is the term for a robot's ability to plan its path avoiding obstacles?",
          optionA: "Kinematics",
          optionB: "Dynamics",
          optionC: "Path Planning",
          optionD: "Localization",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "The study of the forces that cause motion in robots is called:",
          optionA: "Kinematics",
          optionB: "Dynamics",
          optionC: "Statics",
          optionD: "Mechanics",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "Which sensor is commonly used to measure angular velocity in robots?",
          optionA: "Accelerometer",
          optionB: "Gyroscope",
          optionC: "Magnetometer",
          optionD: "Barometer",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "What does ROS stand for in robotics?",
          optionA: "Robotic Operating System",
          optionB: "Robot Operating System",
          optionC: "Remote Operating System",
          optionD: "Realtime Operating System",
          correctAnswer: "B",
          difficulty: "Easy",
        },
      ],
    },
    {
      subject: "iot exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "What does IoT stand for?",
          optionA: "Internet of Things",
          optionB: "Intranet of Things",
          optionC: "Internet of Technology",
          optionD: "Instrument of Technology",
          correctAnswer: "A",
          difficulty: "Easy",
        },
        {
          question: "Which protocol is widely used for lightweight machine-to-machine communications in IoT?",
          optionA: "HTTP",
          optionB: "FTP",
          optionC: "MQTT",
          optionD: "SMTP",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "What is the primary purpose of a gateway in an IoT architecture?",
          optionA: "To power sensors",
          optionB: "To route data between sensors and the cloud",
          optionC: "To display visualizations",
          optionD: "To store logs",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "IPv6 is preferred in IoT because it offers:",
          optionA: "Smaller packet sizes",
          optionB: "Higher security by default",
          optionC: "A massive address space",
          optionD: "Fast routing",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "Which IoT network technology is designed for long-range, low-power communication?",
          optionA: "Bluetooth",
          optionB: "Wi-Fi",
          optionC: "LoRaWAN",
          optionD: "Ethernet",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "What does MQTT stand for?",
          optionA: "Message Queue Telemetry Transport",
          optionB: "Multi-Queue Transfer Technology",
          optionC: "Main Queue Telemetry Transfer",
          optionD: "Message Query Transfer Protocol",
          correctAnswer: "A",
          difficulty: "Easy",
        },
        {
          question: "An actuator in an IoT system is used to:",
          optionA: "Collect environment data",
          optionB: "Perform physical actions based on commands",
          optionC: "Process raw data",
          optionD: "Store database records",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "Which cloud platform is NOT commonly used for IoT data services?",
          optionA: "AWS IoT",
          optionB: "Google Cloud IoT",
          optionC: "Microsoft Azure IoT",
          optionD: "PostgreSQL Cloud",
          correctAnswer: "D",
          difficulty: "Easy",
        },
        {
          question: "What is the main security challenge in IoT devices?",
          optionA: "High CPU processing power",
          optionB: "Heavy resource constraints and lack of encryption",
          optionC: "Too many software updates",
          optionD: "Large battery capacity",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "Which of the following is a hardware prototyping board commonly used in IoT?",
          optionA: "React board",
          optionB: "Raspberry Pi",
          optionC: "Redux board",
          optionD: "Nginx board",
          correctAnswer: "B",
          difficulty: "Easy",
        },
      ],
    },
    {
      subject: "drones exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "What is the technical term for a drone?",
          optionA: "UAV",
          optionB: "UGV",
          optionC: "UUV",
          optionD: "UAW",
          correctAnswer: "A",
          difficulty: "Easy",
        },
        {
          question: "A quadcopter has how many rotors?",
          optionA: "2",
          optionB: "4",
          optionC: "6",
          optionD: "8",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Which component is considered the 'brain' of a drone?",
          optionA: "ESC",
          optionB: "Flight Controller",
          optionC: "LiPo Battery",
          optionD: "PDB",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "What does ESC stand for in drone electronics?",
          optionA: "Electronic Speed Controller",
          optionB: "Electric System Controller",
          optionC: "Emergency Stop Command",
          optionD: "Engine Speed Control",
          correctAnswer: "A",
          difficulty: "Medium",
        },
        {
          question: "What sensor allows a drone to maintain its altitude automatically?",
          optionA: "Magnetometer",
          optionB: "Barometer",
          optionC: "GPS",
          optionD: "Gyroscope",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "How does a drone yaw (rotate around the vertical axis)?",
          optionA: "Increasing speed of all rotors",
          optionB: "Tilting rotors",
          optionC: "Varying speed of opposite rotor pairs",
          optionD: "Changing pitch of blades",
          correctAnswer: "C",
          difficulty: "Hard",
        },
        {
          question: "What is the standard battery chemistry used in hobby and commercial drones?",
          optionA: "NiMH",
          optionB: "Alkaline",
          optionC: "Lead Acid",
          optionD: "LiPo",
          correctAnswer: "D",
          difficulty: "Easy",
        },
        {
          question: "What does FPV stand for in drone piloting?",
          optionA: "First Person View",
          optionB: "Flight Path Vector",
          optionC: "Flight Plan Validation",
          optionD: "Fast Pixels View",
          correctAnswer: "A",
          difficulty: "Easy",
        },
        {
          question: "What is the primary purpose of a gimbal on a drone?",
          optionA: "To protect the motors",
          optionB: "To stabilize the camera",
          optionC: "To increase flight time",
          optionD: "To boost GPS signal",
          correctAnswer: "B",
          difficulty: "Medium",
        },
        {
          question: "Which flight mode holds both altitude and horizontal position using satellites?",
          optionA: "Acro Mode",
          optionB: "AltHold Mode",
          optionC: "GPS Position Hold Mode",
          optionD: "Stabilize Mode",
          correctAnswer: "C",
          difficulty: "Medium",
        },
      ],
    },
    {
      subject: "python exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "Which data type is mutable in Python?",
          optionA: "tuple",
          optionB: "list",
          optionC: "string",
          optionD: "int",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "What is the output of print(2 ** 3)?",
          optionA: "6",
          optionB: "8",
          optionC: "9",
          optionD: "5",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "How do you start a comment in Python?",
          optionA: "//",
          optionB: "/*",
          optionC: "#",
          optionD: "--",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "Which keyword is used to define a function in Python?",
          optionA: "func",
          optionB: "function",
          optionC: "def",
          optionD: "define",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "What does list.append(x) do?",
          optionA: "Add x to the beginning of list",
          optionB: "Add x to the end of list",
          optionC: "Delete x",
          optionD: "Sort the list",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "How do you catch exceptions in Python?",
          optionA: "try/except",
          optionB: "try/catch",
          optionC: "do/catch",
          optionD: "try/fail",
          correctAnswer: "A",
          difficulty: "Medium",
        },
        {
          question: "Which of the following is NOT a built-in Python data collection?",
          optionA: "set",
          optionB: "dictionary",
          optionC: "array",
          optionD: "tuple",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "What is the output of len('Trinetra')?",
          optionA: "7",
          optionB: "8",
          optionC: "9",
          optionD: "10",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "How do you import a module in Python?",
          optionA: "require",
          optionB: "include",
          optionC: "import",
          optionD: "load",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "What does the 'self' keyword represent in a class method?",
          optionA: "The class itself",
          optionB: "The parent class",
          optionC: "The instance of the class",
          optionD: "A global variable",
          correctAnswer: "C",
          difficulty: "Medium",
        },
      ],
    },
    {
      subject: "java exam",
      duration: 30,
      totalQuestions: 10,
      questions: [
        {
          question: "Which keyword is used to inherit a class in Java?",
          optionA: "inherits",
          optionB: "extends",
          optionC: "implements",
          optionD: "super",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "What is the default value of a boolean variable in Java?",
          optionA: "true",
          optionB: "false",
          optionC: "null",
          optionD: "0",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Which package is imported by default in every Java program?",
          optionA: "java.util",
          optionB: "java.io",
          optionC: "java.lang",
          optionD: "java.net",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "What is the size of an int data type in Java?",
          optionA: "16-bit",
          optionB: "32-bit",
          optionC: "64-bit",
          optionD: "8-bit",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Which method is the entry point of any Java application?",
          optionA: "start()",
          optionB: "run()",
          optionC: "main()",
          optionD: "init()",
          correctAnswer: "C",
          difficulty: "Easy",
        },
        {
          question: "How do you declare a constant in Java?",
          optionA: "const",
          optionB: "final",
          optionC: "static",
          optionD: "constant",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Which class is the root class of the Java class hierarchy?",
          optionA: "String",
          optionB: "System",
          optionC: "Object",
          optionD: "Class",
          correctAnswer: "C",
          difficulty: "Medium",
        },
        {
          question: "What is garbage collection in Java?",
          optionA: "Deleting unused files",
          optionB: "Reclaiming unused memory automatically",
          optionC: "Formatting variables",
          optionD: "Handled by compiler",
          correctAnswer: "B",
          difficulty: "Easy",
        },
        {
          question: "Which of these is NOT an access modifier in Java?",
          optionA: "public",
          optionB: "private",
          optionC: "protected",
          optionD: "internal",
          correctAnswer: "D",
          difficulty: "Medium",
        },
        {
          question: "What is the output of '10' + 20 in Java?",
          optionA: "30",
          optionB: "1020",
          optionC: "error",
          optionD: "200",
          correctAnswer: "B",
          difficulty: "Easy",
        },
      ],
    },
  ];

  for (const item of examData) {
    // 2a. Create or update Exam
    const exam = await prisma.exam.upsert({
      where: { subject: item.subject },
      update: {
        duration: item.duration,
        totalQuestions: item.totalQuestions,
      },
      create: {
        subject: item.subject,
        duration: item.duration,
        totalQuestions: item.totalQuestions,
      },
    });

    console.log(`Exam created/updated: ${exam.subject} (ID: ${exam.id})`);

    // 2b. Delete old questions for this exam to prevent duplication upon re-seed
    await prisma.question.deleteMany({
      where: { examId: exam.id },
    });

    // 2c. Seed Questions
    for (const q of item.questions) {
      await prisma.question.create({
        data: {
          examId: exam.id,
          subject: item.subject,
          question: q.question,
          optionA: q.optionA,
          optionB: q.optionB,
          optionC: q.optionC,
          optionD: q.optionD,
          correctAnswer: q.correctAnswer,
          difficulty: q.difficulty,
          questionType: "MCQ",
        },
      });
    }
    console.log(`Seeded ${item.questions.length} questions for ${item.subject}`);
  }

  // 3. Seed Announcements
  const announcementsCount = await prisma.announcement.count();
  if (announcementsCount === 0) {
    await prisma.announcement.createMany({
      data: [
        {
          title: "Trinetra Robotics Workshop 2026",
          description: "Join us for our annual Robotics & Drone workshop next Friday at the HQ. Seats are limited!",
        },
        {
          title: "Exam Portal Launched",
          description: "The official examination portal of Trinetra Drones & Robotics is now live. Students can select their domain and attempt tests.",
        },
      ],
    });
    console.log("Seeded announcements.");
  }

  console.log("Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("Error during seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
