CREATE DATABASE IF NOT EXISTS trinetra;
USE trinetra;

CREATE TABLE IF NOT EXISTS USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE,
  MOBILE VARCHAR(15) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ID_TYPE VARCHAR(30) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL UNIQUE,
  HALL_TICKET VARCHAR(50) NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EXAMS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SLUG VARCHAR(50) NOT NULL UNIQUE,
  TITLE VARCHAR(120) NOT NULL,
  DESCRIPTION TEXT,
  DURATION_MINUTES INT NOT NULL DEFAULT 10,
  TOTAL_QUESTIONS INT NOT NULL DEFAULT 10,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EXAM_ID INT NOT NULL,
  QUESTION_TEXT TEXT NOT NULL,
  OPTION_A VARCHAR(500) NOT NULL,
  OPTION_B VARCHAR(500) NOT NULL,
  OPTION_C VARCHAR(500) NOT NULL,
  OPTION_D VARCHAR(500) NOT NULL,
  CORRECT_OPTION ENUM('a','b','c','d') NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_EXAM_QUESTIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  EXAM_ID INT NOT NULL,
  QUESTION_ID INT NOT NULL,
  DISPLAY_ORDER INT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQUE_USER_EXAM_QUESTION (USER_ID, EXAM_ID, QUESTION_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
  FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_ANSWERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  EXAM_ID INT NOT NULL,
  QUESTION_ID INT NOT NULL,
  SELECTED_OPTION ENUM('a','b','c','d') NULL,
  IS_CORRECT BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQUE_USER_ANSWER (USER_ID, EXAM_ID, QUESTION_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
  FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESULTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  EXAM_ID INT NOT NULL,
  TOTAL_QUESTIONS INT NOT NULL,
  CORRECT_ANSWERS INT NOT NULL,
  SCORE INT NOT NULL,
  PERCENTAGE INT NOT NULL,
  PASSED BOOLEAN NOT NULL DEFAULT FALSE,
  SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQUE_USER_EXAM_RESULT (USER_ID, EXAM_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE
);

INSERT INTO EXAMS (SLUG, TITLE, DESCRIPTION, DURATION_MINUTES, TOTAL_QUESTIONS) SELECT 'reasoning', 'Reasoning Exam', 'Logical thinking, patterns, and problem solving.', 10, 10 WHERE NOT EXISTS (SELECT 1 FROM EXAMS WHERE SLUG='reasoning');
INSERT INTO EXAMS (SLUG, TITLE, DESCRIPTION, DURATION_MINUTES, TOTAL_QUESTIONS) SELECT 'aptitude', 'Aptitude Exam', 'Quantitative aptitude and mathematics.', 10, 10 WHERE NOT EXISTS (SELECT 1 FROM EXAMS WHERE SLUG='aptitude');
INSERT INTO EXAMS (SLUG, TITLE, DESCRIPTION, DURATION_MINUTES, TOTAL_QUESTIONS) SELECT 'coding', 'Coding Exam', 'Programming, DSA, DBMS, and CS basics.', 10, 10 WHERE NOT EXISTS (SELECT 1 FROM EXAMS WHERE SLUG='coding');
INSERT INTO EXAMS (SLUG, TITLE, DESCRIPTION, DURATION_MINUTES, TOTAL_QUESTIONS) SELECT 'gate', 'GATE Exam', 'Engineering aptitude and GATE style questions.', 10, 10 WHERE NOT EXISTS (SELECT 1 FROM EXAMS WHERE SLUG='gate');

INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '2, 4, 8, 16, ?', '18', '24', '32', '36', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='2, 4, 8, 16, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '3, 9, 27, ?', '54', '81', '72', '90', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='3, 9, 27, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find odd: Dog, Cat, Cow, Car', 'Dog', 'Cat', 'Cow', 'Car', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find odd: Dog, Cat, Cow, Car');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'A=1, B=2… LOGIC=?', '46', '47', '48', '49', 'a' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='A=1, B=2… LOGIC=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'AZ, BY, CX, ?', 'DW', 'EV', 'DU', 'FV', 'a' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='AZ, BY, CX, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '1, 4, 9, 16, ?', '20', '25', '30', '36', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='1, 4, 9, 16, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '5, 10, 20, 40, ?', '60', '70', '80', '90', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='5, 10, 20, 40, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '7, 14, 28, ?', '42', '56', '60', '64', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='7, 14, 28, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find next: A, C, E, G, ?', 'H', 'I', 'J', 'K', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find next: A, C, E, G, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Odd one: Apple, Banana, Carrot, Mango', 'Apple', 'Banana', 'Carrot', 'Mango', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Odd one: Apple, Banana, Carrot, Mango');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'If CAT=24, BAT=23, RAT=?', '41', '42', '43', '44', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='If CAT=24, BAT=23, RAT=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Monday, Tuesday, ?', 'Friday', 'Sunday', 'Wednesday', 'Saturday', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Monday, Tuesday, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Cube, Sphere, Cylinder, Circle', 'Cube', 'Sphere', 'Cylinder', 'Circle', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Cube, Sphere, Cylinder, Circle');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '2, 6, 18, 54, ?', '108', '162', '216', '324', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='2, 6, 18, 54, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find odd: Linux, Windows, Oracle, Mac', 'Linux', 'Windows', 'Oracle', 'Mac', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find odd: Linux, Windows, Oracle, Mac');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Z, X, V, T, ?', 'R', 'S', 'Q', 'P', 'a' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Z, X, V, T, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Pen, Pencil, Book, Laptop', 'Pen', 'Pencil', 'Book', 'Laptop', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Pen, Pencil, Book, Laptop');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '2, 3, 5, 7, ?', '9', '10', '11', '12', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='2, 3, 5, 7, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find pair: Doctor:Hospital :: Teacher:?', 'Book', 'School', 'Student', 'Class', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find pair: Doctor:Hospital :: Teacher:?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '3, 6, 9, 12, ?', '13', '14', '15', '16', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='3, 6, 9, 12, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find odd: Tiger, Lion, Elephant, Table', 'Tiger', 'Lion', 'Elephant', 'Table', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find odd: Tiger, Lion, Elephant, Table');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '1, 3, 6, 10, ?', '12', '14', '15', '16', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='1, 3, 6, 10, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'If 8:64 then 6:?', '12', '18', '36', '48', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='If 8:64 then 6:?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Circle, Square, Triangle, Apple', 'Circle', 'Square', 'Triangle', 'Apple', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Circle, Square, Triangle, Apple');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'A, D, G, J, ?', 'L', 'M', 'N', 'O', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='A, D, G, J, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find next: 11, 22, 33, ?', '40', '44', '55', '66', 'b' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find next: 11, 22, 33, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Which odd: CPU, RAM, HDD, Mouse', 'CPU', 'RAM', 'HDD', 'Mouse', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Which odd: CPU, RAM, HDD, Mouse');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find next: 121,144,169,?', '196', '225', '256', '289', 'a' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find next: 121,144,169,?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find odd: Rose, Lily, Lotus, Carrot', 'Rose', 'Lily', 'Lotus', 'Carrot', 'd' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find odd: Rose, Lily, Lotus, Carrot');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '2, 5, 10, 17, ?', '24', '25', '26', '27', 'c' FROM EXAMS E WHERE E.SLUG='reasoning' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='2, 5, 10, 17, ?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '25+17=?', '40', '42', '45', '48', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='25+17=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '15% of 200=?', '20', '25', '30', '35', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='15% of 200=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '12×8=?', '84', '86', '96', '98', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='12×8=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Square of 9?', '72', '81', '91', '99', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Square of 9?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '100÷4=?', '20', '25', '30', '40', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='100÷4=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '7×9=?', '56', '63', '72', '81', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='7×9=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Average of 10,20,30?', '15', '20', '25', '30', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Average of 10,20,30?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '20% of 150?', '20', '25', '30', '35', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='20% of 150?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '11²=?', '111', '121', '131', '141', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='11²=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '144÷12=?', '10', '11', '12', '13', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='144÷12=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'LCM 12,18?', '36', '48', '54', '72', 'a' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='LCM 12,18?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '2x+3=11, x=?', '2', '3', '4', '5', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='2x+3=11, x=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Speed 60km/h for 3h distance?', '120', '150', '180', '200', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Speed 60km/h for 3h distance?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Simple Interest 1000@10% 1yr?', '50', '100', '150', '200', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Simple Interest 1000@10% 1yr?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Ratio 20:40=?', '1:4', '1:3', '1:2', '2:3', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Ratio 20:40=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '5 workers×10 days work?', '40', '50', '60', '70', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='5 workers×10 days work?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '15 km/l for 60km fuel?', '2', '3', '4', '5', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='15 km/l for 60km fuel?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '18+6÷3=?', '6', '8', '20', '24', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='18+6÷3=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Dozen=12, 3 dozen=?', '24', '30', '36', '42', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Dozen=12, 3 dozen=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '500-10% discount=?', '450', '460', '470', '480', 'a' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='500-10% discount=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find %: 50/200?', '10%', '20%', '25%', '30%', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find %: 50/200?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '3²+4²=?', '12', '25', '24', '30', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='3²+4²=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'x²=16, x=?', '2', '4', '-4', '±4', 'd' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='x²=16, x=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Find avg: 5,10,15?', '8', '9', '10', '11', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Find avg: 5,10,15?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '120÷5=?', '20', '22', '24', '25', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='120÷5=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, '8×12=?', '84', '96', '100', '108', 'b' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='8×12=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Area square side 4?', '8', '12', '16', '20', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Area square side 4?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Perimeter square 4?', '8', '12', '16', '20', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Perimeter square 4?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Half of 200?', '50', '75', '100', '150', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Half of 200?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Double of 45?', '80', '85', '90', '95', 'c' FROM EXAMS E WHERE E.SLUG='aptitude' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Double of 45?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Binary search complexity?', 'O(n)', 'O(log n)', 'O(n²)', 'O(1)', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Binary search complexity?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Stack uses?', 'FIFO', 'LIFO', 'Random', 'None', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Stack uses?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Queue uses?', 'FIFO', 'LIFO', 'Tree', 'Graph', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Queue uses?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'BFS complexity?', 'O(V+E)', 'O(n²)', 'O(n)', 'O(log n)', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='BFS complexity?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Primary key?', 'Unique', 'Duplicate', 'Null', 'Optional', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Primary key?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'NoSQL DB?', 'MySQL', 'MongoDB', 'Oracle', 'Postgres', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='NoSQL DB?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Which is OS?', 'Linux', 'Oracle', 'MySQL', 'HTML', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Which is OS?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Quick sort avg?', 'O(n)', 'O(n log n)', 'O(n²)', 'O(log n)', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Quick sort avg?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Deadlock in?', 'CPU', 'OS', 'DB', 'RAM', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Deadlock in?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'SQL fetch?', 'GET', 'SELECT', 'FETCH', 'SHOW', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='SQL fetch?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Normalization removes?', 'Redundancy', 'Speed', 'CPU', 'RAM', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Normalization removes?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Round Robin is?', 'DB', 'CPU scheduling', 'Network', 'Memory', 'b' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Round Robin is?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'DFS uses?', 'Stack', 'Queue', 'Tree', 'Graph', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='DFS uses?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Heap is?', 'Tree', 'Graph', 'Queue', 'Stack', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Heap is?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Index improves?', 'Speed', 'Memory', 'CPU', 'None', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Index improves?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Compiler converts?', 'High→Low', 'Low→High', 'Binary→Text', 'None', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Compiler converts?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Array index starts?', '0', '1', '-1', '2', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Array index starts?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Function recursion?', 'Self-call', 'Loop', 'Jump', 'None', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Function recursion?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'HTTP stands for?', 'HyperText Transfer Protocol', 'HighText', 'Hyper Transfer', 'None', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='HTTP stands for?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Cloud example?', 'AWS', 'CPU', 'RAM', 'USB', 'a' FROM EXAMS E WHERE E.SLUG='coding' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Cloud example?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Derivative of x³?', '3x²', '2x', 'x²', '3x', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Derivative of x³?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'log10(1000)?', '1', '2', '3', '4', 'c' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='log10(1000)?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Determinant [[1,2],[3,4]]?', '-2', '2', '4', '-4', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Determinant [[1,2],[3,4]]?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Eigenvalue identity matrix?', '0', '1', '2', 'n', 'b' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Eigenvalue identity matrix?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Integral 1/x dx?', 'lnx', 'x', 'e^x', 'x²', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Integral 1/x dx?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Solve x²-5x+6=0', '2,3', '1,6', '2,4', '3,4', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Solve x²-5x+6=0');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Probability head coin?', '0', '0.25', '0.5', '1', 'c' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Probability head coin?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'LCM 24,36?', '48', '60', '72', '96', 'c' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='LCM 24,36?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Speed×Time=?', 'Distance', 'Force', 'Work', 'Power', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Speed×Time=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Matrix inverse exists when?', '0', '≠0', '1', '-1', 'b' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Matrix inverse exists when?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'sin²x+cos²x=?', '0', '1', '2', '-1', 'b' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='sin²x+cos²x=?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Rank matrix max?', 'Rows', 'Cols', 'Min', 'Max', 'c' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Rank matrix max?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Laplace eq type?', 'Linear', 'Nonlinear', 'Random', 'None', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Laplace eq type?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Power unit?', 'Watt', 'Volt', 'Ampere', 'Ohm', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Power unit?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Ohm law?', 'V=IR', 'P=VI', 'I=V/R', 'R=VI', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Ohm law?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'FFT complexity?', 'n', 'nlogn', 'n²', 'logn', 'b' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='FFT complexity?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Binary to decimal 101?', '4', '5', '6', '7', 'b' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Binary to decimal 101?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Probability range?', '0-1', '1-10', '-1 to1', '0-100', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Probability range?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Unit vector magnitude?', '0', '1', '2', '∞', 'b' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Unit vector magnitude?');
INSERT INTO QUESTIONS (EXAM_ID, QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_OPTION) SELECT E.ID, 'Integration x dx?', 'x²/2', 'x²', 'x', '1/x', 'a' FROM EXAMS E WHERE E.SLUG='gate' AND NOT EXISTS (SELECT 1 FROM QUESTIONS Q WHERE Q.EXAM_ID=E.ID AND Q.QUESTION_TEXT='Integration x dx?');